name: Trigger Website Build
on:
  issues:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Generate a token
      id: generate_token
      uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Trigger Website Build
      uses: actions/github-script@v5
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
              owner: 'bash',
              repo: 'bash.github.io',
              workflow_id: 'ci.yml',
              ref: 'main',
          });
